@startuml realizacao_pedido_pagamento

!include ./../_common/domainStory.puml
!include ./../_common/icons.puml

title "Realização do Pedido e Pagamento"

' Actors
Person(Cliente)

Boundary(sistema, Sistema) {
    System(Sistema1, Sistema)
    System(Sistema2, Sistema)
    System(Sistema3, Sistema)
}

' Workitems
Document(Pedido1, Pedido)

note top of Pedido1
    Cliente pode
    optar por se
    identificar ou não
end note

Document(Pedido2, Pedido)

Boundary(item_pedido, Itens do Pedido) {
    FA5_HAMBURGER(Lanche, Lanche, label) #White
    FA5_BACON(Acompanhamento, Acompanhamento, label) #White
    FA5_WINE_BOTTLE(Bebida, Bebida, label) #White
    FA5_ICE_CREAM(Sobremesa, Sobremesa, label) #White
}

Boundary(pagamento, Pagamento) {
    GOV_MOBILE(Celular, Celular, label) #White
    FA_QRCODE(QRCode, QR Code, label) #White
}

DEV_DATABASE(bancoDados1, Banco de dados, label) #White
DEV_DATABASE(bancoDados2, Banco de dados, label) #White

' Phases
activity(_, Cliente, inicia, Pedido1, no, Sistema1, <--)
activity(_, Cliente, escolhe, Lanche)
activity(_, Cliente, escolhe, Acompanhamento)
activity(_, Cliente, escolhe, Bebida)
activity(_, Cliente, escolhe, Sobremesa)
activity(_, Cliente, finaliza, Pedido2, no, Sistema2, <--)
activity(_, Sistema2, registra o pedido\ncomo **criado**, bancoDados1)
activity(_, Sistema2, gera o, QRCode)
activity(_, QRCode, é apresentado\npara o, Cliente)
activity(_, Cliente, paga com, Celular, escaneando o, QRCode, <--)
activity(_, QRCode, confirma o\npagamento para o, Sistema3, que registra o pedido\ncomo **pago**, bancoDados2, <--)

@enduml