apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctrl-eat-api
  namespace: fastfood
spec:
  selector:
    matchLabels:
      app: ctrl-eat-api
  template:
    metadata:
      labels:
        app: ctrl-eat-api
    spec:
      serviceAccountName: sa-fastfood        
      containers:
        - name: ctrl-eat-api
          image: jsfelipearaujo/ctrl-eat-api:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "120Mi"
              cpu: "200m"
            limits:
              memory: "240Mi"
              cpu: "400m"
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 1
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: ctrl-eat-api-config
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: password
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "aws-secrets"
