apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctrl-eat-api
  namespace: fastfood
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ctrl-eat-api
  template:
    metadata:
      labels:
        app: ctrl-eat-api
    spec:
      serviceAccountName: sa-fastfood        
      containers:
        - name: ctrl-eat-api
          image: jsfelipearaujo/ctrl-eat-api:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 200Mi
              cpu: 100m
            requests:
              memory: 200Mi
              cpu: 100m
          envFrom:
            - configMapRef:
                name: ctrl-eat-api-config
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: password
            - name: ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: access_key
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: secret_key
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "aws-secrets"
