apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctrl-eat-api
spec:
  selector:
    matchLabels:
      app: ctrl-eat-api
  template:
    metadata:
      labels:
        app: ctrl-eat-api
    spec:
      containers:
        - name: ctrl-eat-api
          image: jsfelipearaujo/ctrl-eat-api:v1.5
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 1
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 1
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: ctrl-eat-api-config
            - secretRef:
                name: ctrl-eat-api-secret
          volumeMounts:
            - name: ctrl-eat-api-vol
              mountPath: /app/images
      volumes:
        - name: ctrl-eat-api-vol
          persistentVolumeClaim:
            claimName: ctrl-eat-api-pv-claim
