apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ctrl-eat-api-hpa
  namespace: fastfood
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ctrl-eat-api
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50