apiVersion: v1
kind: Service
metadata:
  name: ctrl-eat-api
  namespace: fastfood
  labels:
    app: ctrl-eat-api
  annotations:
   service.beta.kubernetes.io/aws-load-balancer-name: lb-fastfood
spec:
  type: LoadBalancer
  loadBalancerClass: service.k8s.aws/nlb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: ctrl-eat-api
