apiVersion: v1
kind: Service
metadata:
  name: ctrl-eat-api
  namespace: fastfood
  labels:
    app: ctrl-eat-api
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: ctrl-eat-api
