apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-pvc
  labels:
    app: api
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
