apiVersion: v1
kind: PersistentVolume
metadata:
  name: ctrl-eat-api-pv-volume
  labels:
    app: ctrl-eat-api
spec:
  storageClassName: api
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
