apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ctrl-eat-api-pv-claim
  labels:
    app: ctrl-eat-api
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
