apiVersion: v1
kind: PersistentVolume
metadata:
  name: ctrl-eat-api-pv-volume
  labels:
    app: ctrl-eat-api
spec:
  storageClassName: hostpath
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /images
