apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-pv
  labels:
    type: local
    app: api
spec:
  capacity:
    storage: 3Gi
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: ./data/ctrl-eat
