apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: fastfood
spec:
  provider: aws
  secretObjects:
    - secretName: database-secret
      type: Opaque
      data:
        - objectName: host
          key: host
        - objectName: username
          key: username
        - objectName: password
          key: password
    - secretName: aws-secret
      type: Opaque
      data:
        - objectName: access_key
          key: access_key
        - objectName: secret_key
          key: secret_key
  parameters:  
    objects: |
      - objectName: "db-fastfood-secret"
        objectType: "secretsmanager"
        jmesPath:
          - path: "host"
            objectAlias: "host"
          - path: "username"
            objectAlias: "username"
          - path: "password"
            objectAlias: "password"
      - objectName: "aws-secret"
        objectType: "secretsmanager"
        jmesPath:
          - path: "access_key"
            objectAlias: "access_key"
          - path: "secret_key"
            objectAlias: "secret_key