apiVersion: v1
kind: Service
metadata:
  name: ctrl-eat-api
  labels:
    app: ctrl-eat-api
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
  selector:
    app: ctrl-eat-api
