apiVersion: v1
kind: PersistentVolume
metadata:
  name: ctrl-eat-db-pv-volume
  labels:
    type: local
    app: ctrl-eat-db
spec:
  storageClassName: db
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
