apiVersion: v1
kind: PersistentVolume
metadata:
  name: ctrl-eat-db-pv-volume
  labels:
    type: local
    app: ctrl-eat-db
spec:
  storageClassName: local-storage-db
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data
