apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ctrl-eat-db-pv-claim
  labels:
    app: ctrl-eat-db
spec:
  storageClassName: local-storage-db
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
