apiVersion: v1
kind: Service
metadata:
  name: ctrl-eat-db
  labels:
    app: ctrl-eat-db
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30001
  selector:
    app: ctrl-eat-db
