version: '3.4'

services:
  app-db:
    image: postgres:16.0
    container_name: CtrlEat.Db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/database:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: "AppDbCtrlEat"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "StrongPassword123"
    ports:
      - "5432:5432"
    networks:
      - api

  pgadmin:
    depends_on:
      - app-db
    image: dpage/pgadmin4:7.8
    container_name: CtrlEat.PgAdmin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    networks:
      - api

  web.api:
    depends_on:
      - app-db
    image: ${DOCKER_REGISTRY-}webapi
    container_name: CtrlEat.Api
    build:
      context: .
      dockerfile: src/External/Web.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DB_NAME=AppDbCtrlEat
      - DB_HOST=app-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=StrongPassword123
    ports:
      - "5001:80"
    networks:
      - api
    volumes:
      - api-data:/app/images

networks:
  api:
    driver: bridge

volumes:
  api-data:
  postgres-data:
  pgadmin-data:
