version: '3.4'

services:
  app-db:
    image: postgres:16.0
    container_name: CtrlEat.Db
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: "AppDbCtrlEat"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "StrongPassword123"
    ports:
      - "5432:5432"
    networks:
      - api

  pgadmin:
    image: dpage/pgadmin4
    container_name: CtrlEat.PgAdmin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - app-db
    networks:
      - api

  web.api:
    depends_on:
      - app-db
    image: ${DOCKER_REGISTRY-}webapi
    container_name: CtrlEat.Api
    build:
      context: .
      dockerfile: src/Adapters/Driving/Web.Api/Dockerfile
    ports:
      - "5001:443"
    networks:
      - api
    volumes:
      - ./.containers/api:/app/images

networks:
  api:
    driver: bridge

volumes:
  pgadmin-data:
