@rootUrl=http://localhost:5001/api/v1

### Create a client
POST {{rootUrl}}/clients
Content-Type: application/json

{
  "firstName": "Francisco",
  "lastName": "Luiz Freitas",
  "email": "francisco_luiz_freitas@zyb.com.br",
  "documentId": "63545117057"
}

### Get all clients
GET {{rootUrl}}/clients

### Get all products categories
GET {{rootUrl}}/products/categories

### Get all product
GET {{rootUrl}}/products

### Create an order
POST {{rootUrl}}/orders
Content-Type: application/json

{
  "clientId": "2ac7ebfc-e8f9-4922-ad24-5a49a918c521"
}

### Get an order
GET {{rootUrl}}/orders/30598ed9-1eb6-4380-babe-9fa5e7ea78fc

### Add a product to the order
POST {{rootUrl}}/orders/30598ed9-1eb6-4380-babe-9fa5e7ea78fc/items
Content-Type: application/json

{
  "productId": "3038eac8-c417-46d6-969c-4bef747cebcd",
  "quantity": 2,
  "observation": null
}

### Pay the order
POST {{rootUrl}}/orders/30598ed9-1eb6-4380-babe-9fa5e7ea78fc/checkout
Content-Type: application/json

### Start the preparation of the order
PATCH {{rootUrl}}/orders/30598ed9-1eb6-4380-babe-9fa5e7ea78fc/status
Content-Type: application/json

{
  "status": "OnGoing"  
}

### After a while, the kitchen finishes the order
PATCH {{rootUrl}}/orders/30598ed9-1eb6-4380-babe-9fa5e7ea78fc/status
Content-Type: application/json

{
  "status": "Done"  
}

### The client sees the order is Done and goes to pick it up
PATCH {{rootUrl}}/orders/30598ed9-1eb6-4380-babe-9fa5e7ea78fc/status
Content-Type: application/json

{
  "status": "Completed"  
}