@rootUrl=https://localhost:5001

### Create a client
POST {{rootUrl}}/clients
Content-Type: application/json

{
  "firstName": "Francisco",
  "lastName": "Luiz Freitas",
  "email": "francisco_luiz_freitas@zyb.com.br",
  "documentId": "63545117057"
}

### Get all clients
GET {{rootUrl}}/clients

### Create a product category
POST {{rootUrl}}/products/categories
Content-Type: application/json

{
  "description": "Hamburguer"
}

### Get all products categories
GET {{rootUrl}}/products/categories

### Create a product
POST {{rootUrl}}/products
Content-Type: application/json

{
  "productCategoryId": "432df276-2353-4fa6-9ad9-6792439cec2e",
  "description": "Hamburguer Especial do Chef",
  "amount": 25.99,
  "currency": "BRL",
  "imageUrl": "http://images-products.com/123456.png"
}

### Get all product
GET {{rootUrl}}/products

### Create an order
POST {{rootUrl}}/orders
Content-Type: application/json

{
  "clientId": "81a43438-c3ac-4074-90e7-7fa359ecc70e"
}

### Get an order
GET {{rootUrl}}/orders/bbe55dc1-de7f-4320-8c93-96f49e2c3c7d

### Add a product to the order
POST {{rootUrl}}/orders/bbe55dc1-de7f-4320-8c93-96f49e2c3c7d/items
Content-Type: application/json

{
  "productId": "fea58b8d-76f3-4bad-ac31-d83ee11b59f6",
  "quantity": 1,
  "observation": null
}