@startuml

!include ./common.puml

!include ./hamburger.puml
!include ./ice_cream.puml
!include ./wine_bottle.puml
!include ./bacon.puml
!include ./qrcode.puml
!include ./mobile.puml
!include ./database.puml
!include ./box.puml
!include ./cutlery.puml

@enduml
